project:
  type: website

website:
  title: "Sidney Bissoli"
  description: "Psychologist, Public Health Researcher, and Financial Markets Analyst"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: publications/index.qmd
        text: Publications
    right:
      - href: "https://linkedin.com/in/sidneybissoli/"
        icon: linkedin
      - href: "mailto:sbissoli76@gmail.com"
        icon: envelope
  page-footer:
    center: |
      Made with [Quarto](https://quarto.org/) by Sidney Bissoli
    background: light

format:
  html:
    theme: cosmo
    fontsize: 1.1em
    linestretch: 1.6
    toc: true
    toc-location: right
    page-layout: article
    css: styles.css