---
title: "Publications"
subtitle: "Academic and Professional Work"
---

## Academic Publications

### Published Papers

**\[**The notion of transference in "Studies on histeria" (Breuer & Freud, 1895)**\]**\
*\[Paidéia\]*\
\[[Link to paper](https://www.scielo.br/j/paideia/a/HkYZXPyFrr4Jp8q4QWxzyzD/)\]

*This article is part of a larger project, in which it intends to examine how the concept of transference is dealt in Freudian's psychoanalysis. As the notion of transference appears by the first time in chapter 4 of "Estudos sobre a histeria", this work acquires the status of the starting point to the examination of that. It verifies that the notion of transference can't ever be understood as the whole relationship that a patient establishes with his psychoanalyst. It can't either be understood as the total perturbation in this type of relationship, as it was further interpreted by other authors. It is only a very specific point of this relationship, in which, through a false bond, and in an uncommon way, the figure of the doctor replaces someone from the patient's past.*

------------------------------------------------------------------------

## R Projects & Analysis

### Featured Work

Visit my [Projects](/projects/) page to see detailed R analysis in:

\- Psychology and behavioral research

\- Public Health data analysis

\- Financial markets research

\- Predictive modeling applications

### RPubs Portfolio

You can also explore my complete portfolio at [RPubs.com/Bissoli](https://rpubs.com/Bissoli).

------------------------------------------------------------------------

*This page will be updated as new publications and projects are completed.*
